// Sample books data
const sampleBooks = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        category: "Fiction",
        price: 12.99,
        description: "Set in the Jazz Age on Long Island, The Great Gatsby tells the story of the mysterious millionaire Jay Gatsby and his obsession with the beautiful Daisy Buchanan. Through the eyes of narrator Nick Carraway, we witness the lavish parties, the decadence, and the ultimate tragedy that unfolds. This classic novel explores themes of the American Dream, wealth, and the emptiness of materialism.",
        image: "https://m.media-amazon.com/images/I/41hG9rp3txL._SY445_SX342_.jpg",
        rating: 4.5,
        reviews: 1200,
        date: "1925-04-10",
        isbn: "978-0743273565",
        pages: 180,
        publisher: "Scribner",
        language: "English",
        dimensions: "5.5 x 0.5 x 8.25 inches",
        weight: "0.5 pounds"
    },
    {
        id: 2,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        category: "Fiction",
        price: 14.99,
        description: "Set in the American South during the 1930s, this Pulitzer Prize-winning novel tells the story of Scout Finch, her brother Jem, and their father Atticus, a lawyer defending a black man falsely accused of a terrible crime. Through the eyes of young Scout, we witness the racial injustice and moral growth that shapes their lives. A powerful exploration of racism, justice, and the loss of innocence.",
        image: "https://m.media-amazon.com/images/I/51IXWZzlgSL._SY445_SX342_.jpg",
        rating: 4.8,
        reviews: 2500,
        date: "1960-07-11",
        isbn: "978-0446310789",
        pages: 336,
        publisher: "Grand Central Publishing",
        language: "English",
        dimensions: "6.4 x 1.1 x 9.2 inches",
        weight: "1.1 pounds"
    },
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        category: "Science Fiction",
        price: 11.99,
        description: "In a dystopian future where the government controls every aspect of life, Winston Smith works at the Ministry of Truth, rewriting history to match the Party's ever-changing version of events. When he begins a forbidden love affair and starts questioning the Party's authority, he risks everything in a world where Big Brother is always watching. A chilling exploration of totalitarianism, surveillance, and the power of language.",
        image: "https://m.media-amazon.com/images/I/51h5bYJzBaL._SY445_SX342_.jpg",
        rating: 4.7,
        reviews: 1800,
        date: "1949-06-08",
        isbn: "978-0451524935",
        pages: 328,
        publisher: "Signet Classic",
        language: "English",
        dimensions: "4.2 x 0.8 x 6.8 inches",
        weight: "0.4 pounds"
    },
    {
        id: 4,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        category: "Romance",
        price: 10.99,
        description: "Set in rural England in the early 19th century, this beloved novel follows the spirited Elizabeth Bennet as she navigates the complex social world of the landed gentry. When the proud Mr. Darcy enters her life, their initial dislike gradually transforms into something deeper. Through witty dialogue and keen social observation, Austen explores themes of love, class, and the importance of first impressions.",
        image: "https://m.media-amazon.com/images/I/51h5bYJzBaL._SY445_SX342_.jpg",
        rating: 4.6,
        reviews: 1500,
        date: "1813-01-28",
        isbn: "978-0141439518",
        pages: 432,
        publisher: "Penguin Classics",
        language: "English",
        dimensions: "5.1 x 1.2 x 7.8 inches",
        weight: "0.7 pounds"
    },
    {
        id: 5,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        category: "Fantasy",
        price: 15.99,
        description: "Bilbo Baggins, a respectable hobbit, is swept into an epic quest when the wizard Gandalf and a company of dwarves arrive at his door. Their mission: to reclaim the dwarves' mountain home and treasure from the fearsome dragon Smaug. Along the way, Bilbo encounters trolls, goblins, elves, and the mysterious creature Gollum, from whom he acquires a magic ring that will change the fate of Middle-earth. A timeless adventure story that serves as a prelude to The Lord of the Rings.",
        image: "https://m.media-amazon.com/images/I/51h5bYJzBaL._SY445_SX342_.jpg",
        rating: 4.9,
        reviews: 3000,
        date: "1937-09-21",
        isbn: "978-0547928227",
        pages: 300,
        publisher: "Houghton Mifflin Harcourt",
        language: "English",
        dimensions: "5.5 x 1.1 x 8.2 inches",
        weight: "0.8 pounds"
    }
]; 